approvalRules:
  - changedFiles:
      allowed:
        - tests/*
        - package.json
        - yarn.lock
    properties:
      - files:
          - package.json
        allowed:
          - dependencies.@babel/*
